### ISSUE TITLE
Usage of Write-Host

### ISSUE THREAD

**Issue by Skons** [the-mentor/nextcloud-powershell#2]
First off I want to thank you for this awesome project :).

Second, on multiple locations Write-Host is used to inform a user about the result of an action. In most cases this should be replaced by Write-Verbose, see the link below for more details on that subject. On line 90 this should be a Write-Error, preferably with the errorcode provided to the user why the authentication has failed.

https://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/

**Comment by Saggiehaim** [comment]
On it :)

**Comment by the-mentor** [comment]
Thank you @Saggiehaim  for the PR.
This issue is resolved.
